USE [master]
GO
/****** Object:  Database [PruebaLisit]    Script Date: 18/08/2021 15:43:17 ******/
CREATE DATABASE [PruebaLisit]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PruebaLisit', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PruebaLisit.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PruebaLisit_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PruebaLisit_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PruebaLisit] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PruebaLisit].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PruebaLisit] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PruebaLisit] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PruebaLisit] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PruebaLisit] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PruebaLisit] SET ARITHABORT OFF 
GO
ALTER DATABASE [PruebaLisit] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PruebaLisit] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PruebaLisit] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PruebaLisit] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PruebaLisit] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PruebaLisit] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PruebaLisit] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PruebaLisit] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PruebaLisit] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PruebaLisit] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PruebaLisit] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PruebaLisit] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PruebaLisit] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PruebaLisit] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PruebaLisit] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PruebaLisit] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PruebaLisit] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PruebaLisit] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PruebaLisit] SET  MULTI_USER 
GO
ALTER DATABASE [PruebaLisit] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PruebaLisit] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PruebaLisit] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PruebaLisit] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PruebaLisit] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PruebaLisit] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PruebaLisit] SET QUERY_STORE = OFF
GO
USE [PruebaLisit]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 18/08/2021 15:43:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 18/08/2021 15:43:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Apellido] [varchar](50) NULL,
	[Mail] [varchar](50) NULL,
	[Edad] [int] NOT NULL,
	[DNI] [int] NOT NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20210818172109_initial', N'5.0.9')
GO
SET IDENTITY_INSERT [dbo].[Usuario] ON 
GO
INSERT [dbo].[Usuario] ([ID], [Nombre], [Apellido], [Mail], [Edad], [DNI]) VALUES (1, N'Lucas', N'Basualdo', N'basualdo1995@gmail.com', 26, 39104528)
GO
INSERT [dbo].[Usuario] ([ID], [Nombre], [Apellido], [Mail], [Edad], [DNI]) VALUES (2, N'Alejo', N'Basualdo', N'@prueba', 25, 39104528)
GO
INSERT [dbo].[Usuario] ([ID], [Nombre], [Apellido], [Mail], [Edad], [DNI]) VALUES (3, N'Oscar', N'Gimenez', N'prueba@', 24, 39104528)
GO
INSERT [dbo].[Usuario] ([ID], [Nombre], [Apellido], [Mail], [Edad], [DNI]) VALUES (4, N'Agustina', N'Holzman', N'@prueba', 20, 123456)
GO
INSERT [dbo].[Usuario] ([ID], [Nombre], [Apellido], [Mail], [Edad], [DNI]) VALUES (5, N'Maia', N'Corbalan', N'@prueba', 25, 123456)
GO
SET IDENTITY_INSERT [dbo].[Usuario] OFF
GO
USE [master]
GO
ALTER DATABASE [PruebaLisit] SET  READ_WRITE 
GO
